# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-17 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EditProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250)),
                ('surname', models.CharField(max_length=500)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('date_of_birth', models.DateField()),
                ('condition', models.CharField(blank=True, choices=[('A', 'Condition A'), ('B', 'Condition B'), ('C', 'Condition C'), ('D', 'Condition D')], max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='relationships',
            fields=[
                ('key', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('mother', models.IntegerField(blank=True, null=True)),
                ('father', models.IntegerField(blank=True, null=True)),
                ('husband', models.IntegerField(blank=True, null=True)),
                ('wife', models.IntegerField(blank=True, null=True)),
                ('attribute', models.CharField(blank=True, choices=[('A', 'Condition A'), ('B', 'Condition B'), ('C', 'Condition C'), ('D', 'Condition D')], max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='sampleTree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tree_name', models.CharField(max_length=250)),
                ('relations', models.CharField(max_length=10000)),
            ],
        ),
    ]
