# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-22 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20170422_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationships',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
