# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-22 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20170422_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationships',
            name='UserID',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
