# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-26 18:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_maintree'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintree',
            name='relations',
        ),
        migrations.DeleteModel(
            name='mainTree',
        ),
    ]
