# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-07 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20170426_1822'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EditProfile',
        ),
        migrations.AlterField(
            model_name='relationships',
            name='attribute',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
