# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-08 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20170508_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationships',
            name='smoker',
            field=models.BooleanField(default=False),
        ),
    ]
